name: Build dist and wheels

on:
  release:
    types:
      - published
jobs:
  build_wheels:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel~=2.3

    - name: Build wheel
      env:
        CIBW_SKIP: "pp*-win* *cp27* *pp*"
        CIBW_BEFORE_BUILD: "pip install torch"
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./wheelhouse
